import 'package:flutter/services.dart';

class GetFlag {
  static const String _flags = 'assets/svg/flags/';
  // static const String afghanistan_flag = flags + "afghanistan.svg";

  static String path(String? countryCode) {
    if (countryCode == null || countryCode.isEmpty) {
      return '${_flags}unmapped_flag.svg';
    }

    countryCode = countryCode.toLowerCase().trim();
    final String path = '$_flags$countryCode.svg';

    if (!path.contains(countryCode)) return '${_flags}jor.svg';

    return path;
  }

  // Get the flag path if it exists, otherwise return null
  static Future<String?> tryPath(String? countryCode) async {
    countryCode = countryCode?.toLowerCase().trim();

    if (countryCode == null || countryCode.isEmpty) {
      return null;
    }

    final String path = '$_flags$countryCode.svg';

    try {
      await rootBundle.load(path);
      return path;
    } catch (error) {
      return null;
    }
  }

  static String? pathFromCurrency(String? currency) {
    if (currency == null || currency.isEmpty) return null;

    currency = currency.toLowerCase();

    if (_getCurrenciesFromCode[currency] != null ||
        _getCurrenciesFromCode.containsKey(currency)) {
      return '$_flags${_getCurrenciesFromCode[currency]}.svg';
    }
    return null;
  }

  static final _getCurrenciesFromCode = {
    'jod': 'jor',
    'usd': 'usa',
    'gbp': 'gbr',
    'eur': 'euro',
    'chf': 'che',
    'cad': 'can',
    'sar': 'sau',
    'aed': 'are',
    'aud': 'aus',
    'bhd': 'bhr',
    'kwd': 'kwt',
    'qar': 'qat',
    'omr': 'omn',
    'egp': 'egy',
    'iqd': 'irq',
    'irr': 'irn',
    'nok': 'nor',
    'afn': 'afg',
    'awg': 'abw',
    'aoa': 'ago',
    'xcd': 'aia',
    'all': 'alb',
    'ax': 'ala',
    'ad': 'and',
    'ars': 'arg',
    'amd': 'arm',
    'as': 'asm',
    'aq': 'ata',
    'tf': 'atf',
    'ag': 'atg',
    'at': 'aut',
    'azn': 'aze',
    'bif': 'bdi',
    'be': 'bel',
    'xof': 'ben',
    'bq': 'bes',
    'bf': 'bfa',
    'bdt': 'bgd',
    'bgn': 'bgr',
    'bsd': 'bhs',
    'bam': 'bih',
    'byn': 'blr',
    'bzd': 'blz',
    'bmd': 'bmu',
    'bob': 'bol',
    'brl': 'bra',
    'bbd': 'brb',
    'bnd': 'brn',
    'btn': 'btn',
    'bv': 'bvt',
    'bwp': 'bwa',
    'xaf': 'caf',
    'cc': 'cck',
    'clp': 'chl',
    'cny': 'chn',
    'cl': 'clv',
    'cm': 'cmr',
    'cdf': 'cod',
    'cg': 'cog',
    'nzd': 'cok',
    'cop': 'col',
    'kmf': 'com',
    'cve': 'cpv',
    'crc': 'cri',
    'cup': 'cub',
    'ang': 'cuw',
    'cx': 'cxr',
    'kyd': 'cym',
    'cy': 'cyp',
    'czk': 'cze',
    'de': 'deu',
    'djf': 'dji',
    'dm': 'dma',
    'dkk': 'dnk',
    'dop': 'dom',
    'dzd': 'dza',
    'ec': 'ecu',
    'eg': 'egy',
    'er': 'eri',
    'mad': 'esh',
    'es': 'esp',
    'ee': 'est',
    'etb': 'eth',
    'fi': 'fin',
    'fjd': 'fji',
    'fkp': 'flk',
    'fr': 'fra',
    'fo': 'fro',
    'fm': 'fsm',
    'ga': 'gab',
    'gel': 'geo',
    'gg': 'ggy',
    'ghs': 'gha',
    'gip': 'gib',
    'gnf': 'gin',
    'gp': 'glp',
    'gmd': 'gmb',
    'gw': 'gnb',
    'gq': 'gnq',
    'gr': 'grc',
    'gd': 'grd',
    'gl': 'grl',
    'gtq': 'gtm',
    'gf': 'guf',
    'gu': 'gum',
    'gyd': 'guy',
    'hkd': 'hkg',
    'hm': 'hmd',
    'hnl': 'hnd',
    'hrk': 'hrv',
    'htg': 'hti',
    'huf': 'hun',
    'idr': 'idn',
    'im': 'imn',
    'inr': 'ind',
    'io': 'iot',
    'ie': 'irl',
    'isk': 'isl',
    'ils': 'isr',
    'it': 'ita',
    'jmd': 'jam',
    'je': 'jey',
    'jpy': 'jpn',
    'kzt': 'kaz',
    'kes': 'ken',
    'kgs': 'kgz',
    'khr': 'khm',
    'ki': 'kir',
    'kn': 'kna',
    'kr': 'kor',
    'krw': 'kor',
    'lak': 'lao',
    'lbp': 'lbn',
    'lrd': 'lbr',
    'lyd': 'lby',
    'lc': 'lca',
    'li': 'lie',
    'lkr': 'lka',
    'lsl': 'lso',
    'lt': 'ltu',
    'lu': 'lux',
    'lv': 'lva',
    'mop': 'mac',
    'ma': 'mar',
    'mc': 'mco',
    'mdl': 'mda',
    'mga': 'mdg',
    'mvr': 'mdv',
    'mne': 'me',
    'mxn': 'mex',
    'mh': 'mhl',
    'mkd': 'mkd',
    'ml': 'mli',
    'mt': 'mlt',
    'mmk': 'mmr',
    'mnt': 'mng',
    'mp': 'mnp',
    'mzn': 'moz',
    'mru': 'mrt',
    'ms': 'msr',
    'mq': 'mtq',
    'mur': 'mus',
    'mwk': 'mwi',
    'myr': 'mys',
    'yt': 'myt',
    'nad': 'nam',
    'xpf': 'ncl',
    'ne': 'ner',
    'nf': 'nfk',
    'ngn': 'nga',
    'nio': 'nic',
    'nu': 'niu',
    'nl': 'nld',
    'no': 'nor',
    'npr': 'npl',
    'nr': 'nru',
    'nz': 'nzl',
    'pkr': 'pak',
    'pab': 'pan',
    'pn': 'pcn',
    'pen': 'per',
    'php': 'phl',
    'pw': 'plw',
    'pgk': 'png',
    'pln': 'pol',
    'pr': 'prl',
    'kpw': 'prk',
    'pt': 'prt',
    'pyg': 'pry',
    'ps': 'pse',
    'pf': 'pyf',
    're': 'reu',
    'ron': 'rou',
    'rub': 'rus',
    'rwf': 'rwa',
    'sdg': 'sdn',
    'sn': 'sen',
    'sgd': 'sgp',
    'gs': 'sgs',
    'shp': 'shn',
    'sj': 'sjm',
    'sbd': 'slb',
    'sll': 'sle',
    'svc': 'slv',
    'sm': 'smr',
    'sos': 'som',
    'pm': 'spm',
    'ssp': 'ssd',
    'stn': 'stp',
    'srd': 'sur',
    'sk': 'svk',
    'sl': 'svn',
    'sek': 'swe',
    'szl': 'swz',
    'scr': 'syc',
    'syp': 'syr',
    'tc': 'tca',
    'td': 'tcd',
    'tg': 'tgo',
    'thb': 'tha',
    'tjs': 'tjk',
    'tk': 'tkl',
    'tmt': 'tkm',
    'tl': 'tls',
    'top': 'ton',
    'ttd': 'tto',
    'tnd': 'tun',
    'try': 'tur',
    'tv': 'tuv',
    'twd': 'twn',
    'tzs': 'tza',
    'ugx': 'uga',
    'uah': 'ukr',
    'um': 'umi',
    'uyi': 'ury',
    'uzs': 'uzb',
    'va': 'vat',
    'vc': 'vct',
    'vef': 'ven',
    'vg': 'vgb',
    'vi': 'vir',
    'vnd': 'vnm',
    'vuv': 'vut',
    'wf': 'wlf',
    'wst': 'wsm',
    'yer': 'yem',
    'zar': 'zaf',
    'zmw': 'zmb',
    'zwl': 'zwe',
    'rur': 'rus',
    'bad': 'bih',
    'ern': 'eri',
    'yu': 'rsd',
    'uyp': 'ury',
    'vib': 'ven'
  };
}
